### ISSUE TITLE
Weird folders set on OpenBSD 6.6

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#197]
I put deluxe to ~/fpcupdeluxe.
expected: it puts all new folders HERE.
reality: it makes new subdir and puts all data THERE. and makes "tmp" there.

```

user$ cd fpcupdeluxe/                                                          
user$ pwd
/home/user/fpcupdeluxe
user$ uname -a
OpenBSD user.my.domain 6.6 GENERIC#353 amd64
user$ ls
fpcup.ini                  fpcupdeluxe-x86_64-openbsd
fpcupdeluxe                settings.ini
user$ ls fpcupdeluxe                                                           
fpcsrc          fpcupdeluxe.ini tmp
user$ ls fpcupdeluxe/tmp                                                       
user$ 
```

**Comment by LongDirtyAnimAlf** [comment]
You have to be more specific with this report.
The latest fpcupdeluxe does not use a global or user local tmp directory anymore.
This gave errors on the latest OSX Cataline, due to permissions.
So, now, even the tmp directory is created inside the base install directory.

If this does not happen, this is a bugger.
So, please be more specific about this.

**Comment by Alexey-T** [comment]
Ok, tmp dir is inside deluxe dir.
Issue is different- both 

Tmp
Fpcsrc

dirs are put into sub folder of fpcupdeluxe folder!

Expected folder- ~/fpcupdeluxe/fpcsrc
Reality- ~/fpcupdeluxe/fpcupdeluxe/fpcsrc

**Comment by LongDirtyAnimAlf** [comment]
This is done to prevent an overwriting of a previous install when a new fpcupdeluxe is started somewhere without knowledge of the previous install.
Some users claimed to have experienced problems due to this. 
So, at first start, fpcupdeluxe will choose an empty dir to be sure not to overwrite.
The correct dir can me set by choosing it the normal way.
