### ISSUE TITLE
disable button in this configuration

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#207]
![Screenshot from 2020-04-04 11-56-09](https://user-images.githubusercontent.com/4154978/78422904-6669a800-766b-11ea-935c-6a500373fdc1.png)

here i checked aarch64+openbsd. so please disable "Remove compiler". you have info about avail cross'es. it is on listbox. shown

**Comment by LongDirtyAnimAlf** [comment]
This would be good to implement.
However, the fpcup(deluxe) design does not make this possible. A lot of trickery would be needed, due to the nature of fpcup inner working.
I have made a start. And perhaps I will finish this. But only after a re-design of the sources. And that may take a while, if ever happening.
Closing for now.
