### ISSUE TITLE
Something wrong with source version detection on 1.6.8x

### ISSUE THREAD

**Issue by gcarreno** [LongDirtyAnimAlf/fpcupdeluxe#257]
Hi Don,

So I was trying to update my "stable" install(Both being under stable so Lazarus 2.0.8) from FPC 3.0.4 to 3.2.0 and did the natural thing:
- Opened `fcpudeluxe` and found the list box was at 3.0.4
- Clicked on the "stable" option (Made sure URL was: https://svn.freepascal.org/svn/fpc/tags/release_3_2_0 and it was)
- Clicked on "FPC Only" button to compile FPC

I'm not completely sure if `fpcupdeluxe` did the correct svn update cuz I got a bit baffled it was saying to me it detected 3.0.4 and was using 3.0.2 to bootstrap. Didn't want to interrupt in the middle, cuz I had a bad experience in the past (Will try it later since you multi thread it :P ) so it ran until success. ( Note: At this time I didn't do a `fpc -iV` to really know what version this compile produced, I'm guessing 3.2.0 because of what happened next... )

My first suspicion was that, somehow, svn update didn't work, cuz there were some patch issues, so I deleted the contents of `fpcsrc` and tried it again. I'll need to open a separate issue, cuz `fpcupdeluxe` 1.6.8x completely failed with an existing, empty `fpcsrc` folder. Makes sense since svn will fail if the folder already exists, but you could test for that? Or is it to much of a small occurring thing that it doesn't matter? Never mind, will post another issue.

So I deleted `fpcsrc` and did another try and was even MORE baffled when I got this:
![fcpupdeluxe-wrong-source-version](https://user-images.githubusercontent.com/81799/86177816-28233e00-bb1f-11ea-91f0-315595b3b37f.png)
The compilation went to be successful and after an `fpc -iV` I got `3.2.0` and I'm fine with it. Nevertheless it's quite suspicious it _kinda_ swapped those versions right?

Cheers,
Gus

**Comment by LongDirtyAnimAlf** [comment]
As you have seen, different versions use different URL. This (switching of URL's) is not something that svn handles very well.
I am thinking about disabling this whole feature and just stop allowing this.
The FPC and Lazarus developers themselves don't support a soft upgrade between versions. So I guess it would be wise to disable this also or fpupdeluxe.

General advice.

Don't upggrade an install. Leave your old install. Make a new install with a new version. That is the correct way of doing this. And you always have your old install as a fallback option !!

About this issue.
Your install seems to be fucked up for sure. Nothing I can do about it. I am not even trying to reproduce such a case. Its caused by fpcupdeluxe not handling this situation very well. Sorry about this. Please refrain from soft-updating and make a new install when a new version is available.

**Comment by LongDirtyAnimAlf** [comment]
This is how I do my installs.
Every install its own directory and its own fpcupdeluxe !

![multiinstall](https://user-images.githubusercontent.com/10783972/86252522-a16c7080-bbb3-11ea-9535-b615dc9a20fa.JPG)

**Comment by gcarreno** [comment]
Hi Don,

I NOW understand the soft update trouble. Mainly there's junk left being from other soft updates and that piles up.

I also have to say, that it's a pain in the tuchus to re-install all your components every time you do an update. Unless you copy `config_lazarus` from one install to the other...

Ok, so no soft installs. Got it. Will close.

Cheers,
Gus
