### ISSUE TITLE
Visual bug for #312

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#313]
In synedit memo in #312 output, I see one line with [0D0A] square chars, it means you put CRLF chars to synedit line?
![22](https://user-images.githubusercontent.com/4154978/96573252-88a8d780-12d6-11eb-8064-2e1fcbcaed25.png)

**Comment by LongDirtyAnimAlf** [comment]
This is the raw output of FPC itself.
Nothing to be done about it by fpcupdeluxe. Can be an utf8 console issue or a codepage to console issue.
Anyhow, I am not going to hunt this bug. Done it in the past on many systems. Hard to solve due to all kinds of language settings and OS versions. Undoable for me as  single person.
