### ISSUE TITLE
Desktop Icon launch path is wrong

### ISSUE THREAD

**Issue by sgmihai** [LongDirtyAnimAlf/fpcupdeluxe#332]
Got this deskop icon file, on Garuda Linux:
[Desktop Entry]
Version=1.0
Encoding=UTF-8
Type=Application
Icon=/home/user/lazarus/lazarus/images/icons/lazarus.ico
Path=/home/user/lazarus/lazarus/
Exec=./lazarus --pcp="/home/user/lazarus/config_lazarus" %f
Name=Lazarus_lazarus
GenericName=Lazarus IDE with Free Pascal Compiler
Category=Application;IDE;Development;GUIDesigner;Programming;
Categories=Application;IDE;Development;GUIDesigner;Programming;
Keywords=editor;Pascal;IDE;FreePascal;fpc;Design;Designer;

Obviously the Exec line is wrong, ./lazarus won't work from desktop
The link in the home folder works though

**Comment by LongDirtyAnimAlf** [comment]
Well. This is by design. The Exec= should work due to the (previous) line Path=
This Path= should be used to find the executable.
Would you mind checking this again ?

If this does not work on your Garuda, would you mind testing if removing the Path= and adding an absolute path into Exec= works ?

Thanks.

**Comment by LongDirtyAnimAlf** [comment]
Closing. No feedback.
