### ISSUE TITLE
Is it possible to provide the gcc compiler with android cross-platform binaries?

### ISSUE THREAD

**Issue by synopse** [LongDirtyAnimAlf/fpcupdeluxe#369]
We use extensively the FpcUpDeluxe cross-bin gcc compilers to cross-compile the mORMot third party C libraries to various platform.
It could be great to have the android platforms supplied with their gcc compilers too - I mean android arm/aarch64/i386/x86_64 of course!
Then we will be able to compile all mORMot supported platforms and let Android build stay in the same SQlite3 version.
Thanks for considering this. With no hurry of course.
;)

**Comment by LongDirtyAnimAlf** [comment]
Will look into this.
Up until now I preferred to use the standard Android SDK and NDK tools as they are available on my system due to Android development work. But a more fpcupdeluxe approach would be welcome indeed.
Keep you informed.

**Comment by LongDirtyAnimAlf** [comment]
New pre-release.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/1.8.2o/fpcupdeluxe-x86_64-linux

Please remove all ./cross/bin/*-android bintools directories.
Let this pre-release install a new android-crossinstaller. This way, the new universal tools will be downloaded and installed.
Please note: clang is used due to gcc no longer provided for Android.

Buildscript:
(for aarch64 use --target=aarch64-linux-android29)
(for x64 use --target=x86_64-linux-android29)
(for i386 use --target=i686-linux-android29)

#!/bin/sh

ARCH=arm-android

CROSS=/home/superdad/Public/trunk/cross/bin/all-android/
GCC=$CROSS/bin/clang

DST=./static/$ARCH/sqlite3.o

mkdir -p ./static/$ARCH

rm $DST
rm sqlite3-$ARCH.o

echo
echo ---------------------------------------------------
echo Compiling for FPC on $ARCH using $GCC
$GCC --target=armv7a-linux-androideabi29 -static -O2 -Wno-pointer-sign -DNDEBUG -DNO_TCL -D_CRT_SECURE_NO_DEPRECATE -D__ARM_PCS_VFP -c sqlite3mc.c -o sqlite3-$ARCH.o

$CROSS/bin/llvm-strip sqlite3-$ARCH.o

cp sqlite3-$ARCH.o $DST

Have fun. I hope all will work.

**Comment by synopse** [comment]
It seems to work just fine.

It is GREAT FUN indeed!
Thanks :+1:
