### ISSUE TITLE
Wish: verbose log - auto-scroll auto-disable

### ISSUE THREAD

**Issue by the-Arioch** [LongDirtyAnimAlf/fpcupdeluxe#485]
A.S. i tried to open `fpcupdeluxemainform` but as soon as i hi F12 to switch to form designer - Lazarus/win64 crashes. There is some error about property value range - but before i can read it it crashes hardly...

---

Can you implement a feature i saw in VisualIRC client?

```
Welcome @ FPCUPdeluxe.
FPCUPdeluxe V2.2.0h for x86_64-win64-win32
```

This main log window, can you alter it's behavior if user scrolls it by mouse wheel?

1. If the last line is visible - behave like now, every new added line keeps it scrolling down
2. If the last line is not visible - assume user scrolled it and want to take time to read something, then...
3. ...then make visible "AutoScroll" SpeedButton in the bottom right corner (with a small margin liek 2px) of the log widget .ClientRect
4. ...also then added lines should not trigger auto-scroll
5. When user clicks "AutoScroll" SpeedButton - scroll to the end, reverting to current, default, auto-scrolling behavior
6. ...and hide the "AutoScroll" SpeedButton button in default mode too

Should not be that hard, but i failed to open sources and look into it :-)

**Comment by LongDirtyAnimAlf** [comment]
As I do agree that this feature would be nice, I do not wish to implement this.
There have been other requests for the log windows.
However, fpcupdeluxe is just an installer. GUI features are limited by design. They consume time and are not that easy to implement due to the fact that a command line application is the base of everything, with a lot of hacks to get the output in a GUI.
