### ISSUE TITLE
Error in fpc.cfg for xtensa targets

### ISSUE THREAD

**Issue by michael-ring** [LongDirtyAnimAlf/fpcupdeluxe#487]
There is a little mess in the config for xtensa targets. This is what i get in a fresh fpc.cfg on Linux (Fedora):

```
# Cross compile settings dependent on both target OS and target CPU
#IFDEF FPC_CROSSCOMPILING
#IFDEF FREERTOS
#IFDEF CPUXTENSA
#IFDEF CPULX6
-Cfhard
-Fl/home/ring/fpcupdeluxe/cross/lib/xtensa-freertos/lx6/
#ENDIF CPULX6

#IFDEF CPULX106
-Fl/home/ring/fpcupdeluxe/cross/lib/xtensa-freertos/lx106/
#ENDIF CPULX106

-FD/home/ring/fpcupdeluxe/cross/bin/xtensa-freertos/bin/


```
Now the mess starts:

```
-XPxtensa-lx106-elf-
-Wpesp8266

-Ff/home/ring/fpcupdeluxe/cross/bin/xtensa-freertos/esp-idf-4.1.1
-WP3.4

```
This is a mix between things for lx106 (which should go in the lx106 section) and stuff for lx6 (the esp-idf-4.1.1)

```
-Fu/home/ring/fpcupdeluxe/fpc/units/xtensa-freertos/$FPCSUBARCH/rtl
-Fu/home/ring/fpcupdeluxe/fpc/units/xtensa-freertos/$FPCSUBARCH/packages
#ENDIF CPUXTENSA
#ENDIF FREERTOS
#ENDIF FPC_CROSSCOMPILING

```

**Comment by michael-ring** [comment]
I have now all the bits and peaces in place and grep'ed a little through the fpcupdeluxe sources. There is some hardcoded stuff that will bite us in future releases (as it currently bites us, one obvious example:

```
        S:='';
        if (FSubArch=TSUBARCH.lx6) then S:='4.2';
        if (FSubArch=TSUBARCH.lx106) then S:='3.4';

```
from m_any_to_freertosxtensa.pas

what I would like to propose is a template that comes with esptools4fpc that, when found is used to generate the needed fpc.cfg settings. you'd need to replace {{deluxebasedir}} with the basedir of the deluxe installation (i can change deluxedir to whatever sounds better to you and is more consistent with fpcupdeluxe ....)
I have not yet testen lx106 linker path's so the example below may only be 95% complete.

```
# begin fpcup do not remove xtensa-freertos
# Inserted by fpcup 11-1-22 10:25:35
# Cross compile settings dependent on both target OS and target CPU
#IFDEF FPC_CROSSCOMPILING
#IFDEF FREERTOS
#IFDEF CPUXTENSA
#IFDEF CPULX6
-Cfhard
-Wpesp32
-WP4.3
-XPxtensa-esp32-elf-
-Ff{{deluxebasedir}}/cross/bin/xtensa-freertos/esp-idf-4.3.2
-Fl{{deluxebasedir}}/cross/lib/xtensa-freertos/lx6/
-Fl{{deluxebasedir}}/cross/bin/xtensa-freertos/esp-idf-4.3.2/components/esp_rom/esp32/ld/
-Fl{{deluxebasedir}}/cross/bin/xtensa-freertos/esp-idf-4.3.2/components/esp32/ld/
#ENDIF CPULX6
#IFDEF CPULX106
-Wpesp8266
-WP3.4
-XPxtensa-lx106-elf-
-Ff{{deluxebasedir}}/cross/bin/xtensa-freertos/esp-rtos-3.4
-Fl{{deluxebasedir}}/cross/lib/xtensa-freertos/lx106/
-Fl{{deluxebasedir}}/cross/bin/xtensa-freertos/esp-rtos-3.4/components/esp8266/ld/
#ENDIF CPULX106
-FD{{deluxebasedir}}/cross/bin/xtensa-freertos/bin/
-Fu{{deluxebasedir}}/fpc/units/xtensa-freertos/$FPCSUBARCH/rtl
-Fu{{deluxebasedir}}/fpc/units/xtensa-freertos/$FPCSUBARCH/packages
#ENDIF CPUXTENSA
#ENDIF FREERTOS
#ENDIF FPC_CROSSCOMPILING
# end fpcup do not remove 
```

**Comment by michael-ring** [comment]
Works nicely now on my mac.

when you clone my fork of christo's code you can go to the examples directory and open + compile (most of) them.
https://github.com/michael-ring/fpc-esp-freertos

I have created a pull request for Christo as his original examples have some hardcoding of paths in the lpi files so they do not work out of the box.

**Comment by LongDirtyAnimAlf** [comment]
I have one remaining question.

There are paths with a version inside. Like 3.4 or 4.3.2 or whatever.
We also set the -WP compiler switch.
I would like to join these: so use the -WP version also for the paths.

Reason.

I would like the final fpcupdeluxe user to only have to set the -WPxxx in the custom cross-compile options.
Using this setting, all binary and library tool paths can be set by using this xxx version.
Allowing for softcoded upgrades of the tools without the need of an upgraded fpcupdeluxe.

Example:

Set -WP4.6 in cross-options.
Tools with 4.6 in their paths are used.

Now:

We set -WP4.3
Tools have 4.3.2 in their path and version cannot be used to find these.

Thanks !!

**Comment by michael-ring** [comment]
That's a good question for Christo's opinion how to best solve that, I honestly did not give it much thought, perhaps there is already a way to reach this goal. Not sure if he's subscribed to this issue, I will send him an e-mail and point him to this discussion....

**Comment by ccrause** [comment]
This may be a bit long, I will start at the back.  Do we want a user to specify a particular version of the SDK tools/libraries?  This is probably required to maintain compatibility with a slightly older user code base.  The problem then is how to detect the appropriate release to download from https://github.com/michael-ring/espsdk4fpc/releases. Another potential problem is that both esp8266 & esp32 SDKs are bundled in one  archive, so a both versions are linked via whatever release cycle is followed on espsdk4fpc.

On to solutions: A possible fix is to hard code the mapping from SDK versions to release name (but these will have to be a combination of esp32 & esp68266 versions).  Something as follows:

(esp-idf-4.3.2 & esp-rtos-3.4) => download https://github.com/michael-ring/espsdk4fpc/releases/tag/v1.1.0-4 [default currently]
(esp-idf-4.1.1 & esp-rtos-3.3) => download https://github.com/michael-ring/espsdk4fpc/releases/tag/v1.0.0-3

Since the SDKs and bintools for different subarches are lumped in espsdk4fpc, it also creates a strong link between installing the lx6 and lx106 subarches.  To get something out the door for now, this can be left as is, but in future I think the SDK version management would be easier if either the SDK archives are split according subarch, or the concept of subarch is ignored for xtensa-freertos and both lx6 and lx106 are automatically installed.

Then the original question, SDK versions and paths.  The latest (yesterday) xtensa patch for FPC takes patch level into consideration, so one can specify the full version string as -WP4.3.2.  This then allows one the use a single variable per controller to hold the version and insert this for -WP and in the library path pointing to the lib folder inside the esp-idf-xxx or esp-rtos-yy folders.

Looking at the future, the esp-idf SDK already supports both lx6 (esp32) and lx7 (esp32-s2/3) controllers, and eventually the esp8266 will join esp-idf, so it isn't clear what the best path forward is.

Sorry for all the tangents, I guess the focus should be to implement something that works for xtensa.

**Comment by LongDirtyAnimAlf** [comment]
Good info. Thanks ! Looking forward towards more integration for xtensa.
To finalize the current implementation, one remaining decision.
If fpcupdeluxe is used/asked to install xtensa lx6/lx106 shall it use:
* -WP4.3.2 and transport this towards the paths needed.
* -WP4.3 and use fixed paths for now.
