### ISSUE TITLE
About menu item

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#545]
I must say the location of About item in the menu root is bad from UX point of view. on macOS, I click the upper menu, move mouse left-right and this causes About popup when I move over 'About'. bad UX. Better move About item into submenu or into 'File'.

**Comment by CCRDude** [comment]
Came here for exactly that issue. Have been using fpcupdeluxe for years, and the UI is kind of functionality instead of usability focused. Was about to post an issue myself that the top level menu should not include actions, just submenues.

Usually, it's a Help submenu that includes the About. And then it needs to be called About... - the end ellipsis is an indicator that this will open a form.

**Comment by CCRDude** [comment]
The move-cursor-behaviour is macOS only - the bad UI design is general ;)

**Comment by LongDirtyAnimAlf** [comment]
Please test.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/test_release

**Comment by Alexey-T** [comment]
'About' item is now OK. Tks.
`Languages / Ukrainian (UK)` - Ukraine ISO code is `UA`.
