### ISSUE TITLE
New OS for cross-compiling `linux-legacy`, what is it?

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#606]
Let's write the info about this new OS so ppl can find it via GitHub search.

![leg](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/assets/4154978/61d444b5-2531-43bc-9dc5-607bfa97a8b9)

**Comment by LongDirtyAnimAlf** [comment]
There were reported some issues with the versioned linking by FPC. Search the forum for these messages (unversioned linking).
A binary compiled on a new version of Linux will not run on an old version of Linux. Due to glibc versioning issues.
Linux-legacy will download libraries from a fairly old Linux (Ubuntu 16). The cross-compiled binaries will run on old and new Linux versions.
At least I hope.
