### ISSUE TITLE
Does `fpcupdeluxe` detect when there are new cross libs?

### ISSUE THREAD

**Issue by gcarreno** [LongDirtyAnimAlf/fpcupdeluxe#619]
Hey @LongDirtyAnimAlf,

I've installed my cross compilers quite a while ago and, if I'm not mistaken, there's been an update on some of the cross libs since then.

Does `fpcupdeluxe` make any checks to home do determine if there are updated cross libs?

If not, what is the best way to trigger a new download?

Many thanks in advance!!

Cheers,
Gus

**Comment by LongDirtyAnimAlf** [comment]
No. Fpcupdeluxe does not check if new libs are available.
This is due to the fact that new libs are not always desirable. The newest libs will produce binaries that will not work on older systems. See the Lazarus forum messages about GLIBC versions causing errors.
So, this will never be implemented.

**Comment by gcarreno** [comment]
Hey Don(@LongDirtyAnimAlf),

:thinking: Hummmm, you do make a very good point.

Would some kind of boolean option, or a button make sense for those that "_know_" what they're doing?

I dunno, sumthin' along these lines?

Cheers,
Gus
