### ISSUE TITLE
v2.4.0d refuses to run (it won't even start): symbol lookup error

### ISSUE THREAD

**Issue by prof7bit** [LongDirtyAnimAlf/fpcupdeluxe#682]
./fpcupdeluxe-x86_64-linux-qt5: symbol lookup error: ./fpcupdeluxe-x86_64-linux-qt5: undefined symbol: QGuiApplication_setFallbackSessionManagementEnabled

Version: v2.4.0d
OS: Ubuntu 22.04.4 LTS (Kubuntu)

Older versions not yet tested

**Comment by prof7bit** [comment]
2.0.4c runs, but I cannot build anything anymore, no matter what combination of fpc and lazarus I try, it will fail eithetr fpc build or lazarus build with cryptic errors :-(

Thank god I have made a backup of m woking lazarus before I attempted to update it.

I wish FPC/Laz would have a proper functioning build system like most other software, the amount of problems and workarounds in the build process with EVERY new minor version is truly ridiculous :-(

**Comment by LongDirtyAnimAlf** [comment]
A normal install should be done by the package manager of the Linux system itself. And that should work out of the box.
And yes, the build-system of FPC is not easy. And fpcupdeluxe has a hard job handling all of its quirks. And qt4/5/6 makes life a bit more difficult.
About this issue.
This is caused by changes in the libqt library. Not much can be done. Except from building the latest libqt on every system available. The Lazarus forum can help.
